### ISSUE TITLE
App unsafe with Google alert

### ISSUE THREAD

**Issue by crimsonpixel** [lossendae/BigBrother#45]
Hi there,

I've downloaded and installed on a couple of new sites, but I'm getting the following message.  I do continue to go through to get the code, but just thought I'd flag it up.  I guess this extra needs approval from Google...
![bigbrother-issue](https://user-images.githubusercontent.com/2063237/69955585-e6350980-14f5-11ea-8924-226b9a1fb7a6.png)

**Comment by lossendae** [comment]
This uses google analytics which have probably evolved a lot since this extra was made. It doesn't surprise me that it does not respect the latest service policies required by google.

I'm not  using modx anymore, therefore, it's complicated for me to give you any pointer to make it work correctly. 

As specified on the front page, @Mark-H maintains this extra on his own repository, som I invite you to continue discussing this issue there: https://github.com/modmore/BigBrother/issues/33
